openapi: 3.0.0
info:
  title: Rental Service API
  description: The API for managing vehicle rentals
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/NIZOLEMAKOMA4_1/rentals/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/NIZOLEMAKOMA4_1/RentalService/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /rentals:
    get:
      tags:
      - Rental
      description: Returns all available rentals
      operationId: getRentals
      parameters:
      - name: skip
        in: query
        description: Number of records to skip
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: Max number of records to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: A list of available rentals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rental'
    post:
      tags:
      - Rental
      description: Create a new rental listing
      operationId: createRental
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rental'
        required: true
      responses:
        "201":
          description: Rental created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rental'
  /rentals/{rentalId}:
    get:
      tags:
      - Rental
      operationId: getRentalDetails
      parameters:
      - name: rentalId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Rental details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rental'
        "404":
          description: Rental not found
components:
  schemas:
    Rental:
      type: object
      properties:
        vehicle:
          type: string
          description: The vehicle being rented
        longitude:
          type: number
          description: Longitude of the rental location
          format: float
        latitude:
          type: number
          description: Latitude of the rental location
          format: float
        location:
          type: string
          description: Description of the rental location
        availability:
          type: boolean
          description: Indicates if the vehicle is available for rent