openapi: 3.0.0
info:
  title: Transportation Schedule API
  description: The API for managing transportation schedules
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/NIZOLEMAKOMA4_1/Transportation/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /schedules:
    get:
      tags:
      - Schedule
      description: Returns all transportation schedules
      operationId: getSchedules
      parameters:
      - name: skip
        in: query
        description: Number of records to skip
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: Max number of records to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: A list of transportation schedules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
    post:
      tags:
      - Schedule
      description: Create a new transportation schedule
      operationId: createSchedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
        required: true
      responses:
        "201":
          description: Schedule created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
  /schedules/{scheduleId}:
    get:
      tags:
      - Schedule
      operationId: getScheduleDetails
      parameters:
      - name: scheduleId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Schedule details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        "404":
          description: Schedule not found
components:
  schemas:
    Schedule:
      type: object
      properties:
        routeName:
          type: string
          description: The name of the route
        stops:
          type: array
          description: List of stops on the route
          items:
            type: string
        schedule:
          type: string
          description: The scheduled time for the route
        days:
          type: array
          description: Days on which the route operates
          items:
            type: string
            enum:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday